// Code generated by "golang-cloudformation". DO NOT EDIT.

package {{ .MustGetGoBasePackageName }}

{{ if .MustGetGoImports }}
    import (
        {{- range .MustGetGoImports -}}
            "{{ . }}"
        {{ end }}
    )
{{ end }}

{{ if .IsTopLevelResourceType }}
var (
    _ cfz.ResourcePartialLogicalName = (*{{ .MustGetGoBaseStructName }})(nil)
    _ cfz.Resource = (*{{ .MustGetGoBaseStructName }})(nil)
)
{{ end }}

const (
    {{ .MustGetGoBaseStructName }}__Type = "{{ .Name }}"
)

{{ if .Attributes }}
var (
    {{ .MustGetGoBaseStructName }}__AttributesMap = struct {
        {{ range $k, $v := .Attributes -}}
            {{ $v.MustGetGoFieldName }} string
        {{ end }}
    }{
        {{ range $k, $v := .Attributes -}}
            {{ $v.MustGetGoFieldName }}: "{{ $v.Name }}",
        {{ end }}
    }

    {{ .MustGetGoBaseStructName }}__AttributesSlice = []string{
        {{ range $k, $v := .Attributes -}}
            {{ $.MustGetGoBaseStructName }}__AttributesMap.{{ $v.MustGetGoFieldName }},
        {{ end }}
    }
)
{{ end }}

{{ if .Properties }}
var (
    {{ .MustGetGoBaseStructName }}__PropertiesMap = struct {
        {{ range $k, $v := .Properties -}}
            {{ $v.MustGetGoFieldName }} string
        {{ end }}
    }{
        {{ range $k, $v := .Properties -}}
            {{ $v.MustGetGoFieldName }}: "{{ $v.Name }}",
        {{ end }}
    }

    {{ .MustGetGoBaseStructName }}__PropertiesSlice = []string{
        {{ range $k, $v := .Properties -}}
            {{ $.MustGetGoBaseStructName }}__PropertiesMap.{{ $v.MustGetGoFieldName }},
        {{ end }}
    }
)
{{ end }}

// {{ .MustGetGoBaseStructName }} is a binding for {{ .Name }}.
// See: {{ .Documentation }}
type {{ .MustGetGoBaseStructName }} struct {
    {{ if .IsTopLevelResourceType -}}
        // CF_LogicalName is the CloudFormation logical name for this resource in the template.
        CF_LogicalName string `json:"-"`

        // CF_DependsOn indicates which resources must be created before this one.
        CF_DependsOn []cfz.ResourcePartialLogicalName `json:"-"`
    {{ end }}

    {{- range $k, $v := .Properties }}
        // {{ $v.Name }} is a resource property.
        // Required: {{ $v.Required }}
        // Update: {{ $v.UpdateType }}
        // See: {{ $v.Documentation }}
        {{ $v.MustGetGoFieldName }} {{ $v.MustGetGoBaseType }} `json:"{{ $v.Name }},omitempty"`
    {{ end }}
}

{{ if .IsTopLevelResourceType }}
    // GetLogicalName returns the CloudFormation logical name for this resource in the template.
    // It implements the cfz.Resource and cfz.ResourcePartialLogicalName interface.
    func (v *{{ .MustGetGoBaseStructName }}) GetResourceLogicalName() string {
        return v.CF_LogicalName
    }
{{ end }}

// GetType returns the CloudFormation type.{{ if .IsTopLevelResourceType }}
// It implements the cfz.Resource interface.{{ end }}
func (v *{{ .MustGetGoBaseStructName }}) GetType() string {
    return {{ .MustGetGoBaseStructName }}__Type
}

{{ if .IsTopLevelResourceType }}
    // Ref returns an Expression[string] that resolves to the Ref intrinsic function for this resource.
    func (v *{{ .MustGetGoBaseStructName }}) Ref() cfz.Expression[string] {
        return cfz.Ref(cfz.V(v.GetResourceLogicalName()))
    }

    {{ range $k, $v := .Attributes }}
        {{ if $v.IsGoExpressionSlice }}
            // GetAttSlice__{{ $v.MustGetGoFieldName }} returns an ExpressionSlice[{{ $v.MustGetGoBaseGenericType }}] that resolves to the FN::GetAtt intrinsic function for this resource.
            // Attribute: {{ $v.Name }}
            func (v *{{ $.MustGetGoBaseStructName }}) GetAttSlice__{{ $v.MustGetGoFieldName }}() {{ $v.MustGetGoBaseType }} {
                return cfz.GetAttSlice[{{ $v.MustGetGoBaseGenericType }}](cfz.V(v.GetResourceLogicalName()), cfz.V({{ $.MustGetGoBaseStructName }}__AttributesMap.{{ $v.MustGetGoFieldName }}))
            }
        {{ else }}
            // GetAtt__{{ $v.MustGetGoFieldName }} returns an Expression[{{ $v.MustGetGoBaseGenericType }}] that resolves to the FN::GetAtt intrinsic function for this resource.
            // Attribute: {{ $v.Name }}
            func (v *{{ $.MustGetGoBaseStructName }}) GetAtt__{{ $v.MustGetGoFieldName }}() {{ $v.MustGetGoBaseType }} {
                return cfz.GetAtt[{{ $v.MustGetGoBaseGenericType }}](cfz.V(v.GetResourceLogicalName()), cfz.V({{ $.MustGetGoBaseStructName }}__AttributesMap.{{ $v.MustGetGoFieldName }}))
            }
        {{ end }}
    {{ end }}

    // MarshalJSON implements the cfz.Resource interface.
    func (v *{{ .MustGetGoBaseStructName }}) MarshalJSON() ([]byte, error) {
        if v == nil {
            return []byte(`null`), nil
        }

        type CF_Properties {{ .MustGetGoBaseStructName }}

        return json.Marshal(struct {
            Type string `json:"Type"`
            DependsOn []string `json:"DependsOn,omitempty"`
            Properties *CF_Properties `json:"Properties,omitempty"`
        }{
            Type: v.GetType(),
            DependsOn: v.getDependsOn(),
            Properties: (*CF_Properties)(v),
        })
    }

    func (v *{{ .MustGetGoBaseStructName }}) getDependsOn() []string {
        dependsOn := make([]string, 0, len(v.CF_DependsOn))

        for _, r := range v.CF_DependsOn {
            dependsOn = append(dependsOn, r.GetResourceLogicalName())
        }

        return dependsOn
    }
{{ end }}